version = 0.1
[default.deploy.parameters]
stack_name = "recall-api-stack"
resolve_s3 = true
s3_prefix = "recall-api-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KnowledgeBaseId=\"BOHIJSPM7T\" ModelId=\"anthropic.claude-3-haiku-20240307-v1:0\""
image_repositories = []
disable_rollback = true
